packages:
  python:
    externals:
    - spec: python@3.10.12+bz2+crypt+ctypes+dbm+lzma+pyexpat~pythoncmd+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.8.0
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  ninja:
    externals:
    - spec: ninja@1.10.1
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.22.1
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.34.0~cpanm+opcode+open+shared+threads
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.8.2
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.38+gold~headers
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@3.0.2
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.9p1
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.21
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.8
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.81.0+gssapi+ldap+nghttp2
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.0.2
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.8
      prefix: /usr
  git:
    externals:
    - spec: git@2.34.1~tcltk
      prefix: /usr
  gcc:
    externals:
    - spec: gcc@11.4.0 languages:='c,c++,fortran'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
    - spec: gcc@12.3.0 languages:='c,c++,fortran'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc-12
          cxx: /usr/bin/g++-12
          fortran: /usr/bin/gfortran-12
  llvm:
    externals:
    - spec: llvm@14.0.0+clang~flang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang
          cxx: /usr/bin/clang++
    - spec: llvm@15.0.7+clang~flang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang-15
          cxx: /usr/bin/clang++-15
